name: 🧪 Runtime Compatibility Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  deno:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno task build
      - run: deno task test

  node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: node
      - run: npm install --no-save dayjs
      - run: npm exec --yes tsx test/node-smoke.ts

  bun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun test/bun-smoke.ts

  browser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: node
      - run: npm install --no-save vitest @vitest/browser-playwright dayjs
      - run: npx playwright install chromium
      - run: npx vitest run --browser.enabled --browser.headless test/browser-smoke.test.ts
